# A Job creates one or more Pods and will continue to retry execution of the Pods until a specified number of them successfully terminate. As pods successfully complete, the Job tracks the successful completions. When a specified number of successful completions is reached, the task (ie, Job) is complete. Deleting a Job will clean up the Pods it created. Suspending a Job will delete its active Pods until the Job is resumed again.

# A simple case is to create one Job object in order to reliably run one Pod to completion. The Job object will start a new Pod if the first Pod fails or is deleted (for example due to a node hardware failure or a node reboot).

# You can also use a Job to run multiple Pods in parallel.

# also daemonsets, replicasets ....

# kubectl apply -f deployments/06-job.yaml
# kubectl delete -f deployments/06-job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: destroy-techmunch
spec:
  template:
    spec:
      containers:
        - name: techmunch
          image: sjnarmstrong/techmunch-sholto:20210717
          imagePullPolicy: Always
          command: ["python3", "app.py", "-j"]
      restartPolicy: Never
  backoffLimit: 4