# kubectl apply -f deployments/09-secrets.yaml
# kubectl delete -f deployments/09-secrets.yaml
# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
  name: techmunch-secret
data:
  # property-like keys; each key maps to a simple value
  config_property_1: "VGhpcyBpcyBub3QgYSBzZWNyZXQgdmFsdWUuLi4uIE9yIGlzIGl0Cg=="
  config_property_2: "VGhpcyBpcyBhIHNlY3JldCB2YWx1ZQo="
  file: "U3RpbGwgRWxvbgo="
---
apiVersion: v1
kind: Service
metadata:
  name: techmunch-headless
  labels:
    app: techmunch-headless
spec:
  clusterIP: None
  selector:
    app: techmunch
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: techmunch
spec:
  selector:
    matchLabels:
      app: techmunch
  serviceName: techmunch-headless
  replicas: 3 
  template:
    metadata:
      labels:
        app: techmunch 
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: techmunch
          image: sjnarmstrong/techmunch-sholto:20210717
          imagePullPolicy: Always
          ports:
            - containerPort: 8888
              protocol: TCP
              name: http
          resources:
            requests:
              memory: "500Mi"
              cpu: "1000m"
            limits:
              memory: "500Mi"
              cpu: "1000m"
          env:
            - name: APP_CONFIG
              valueFrom:
                secretKeyRef:
                  name: techmunch-secret
                  key: config_property_1
            - name: APP_SECRET_CONFIG
              valueFrom:
                secretKeyRef:
                  name: techmunch-secret
                  key: config_property_2
          volumeMounts:
            - name: config
              mountPath: "/etc/namesvol"
              readOnly: true
      volumes:
        - name: config
          secret:
            secretName: techmunch-secret
            # items:
            # - key: "config_property_name"
            #   path: "file"